name: Create EC2 instances
description: Creates EC2 instances

inputs:
  region:
    description: 'The AWS region used to host the EC2 instances.'
    required: true

runs:
  using: composite
  steps:
    - id: aws-ec2-requirements-install
      name: Install the required Ansible AWS collections.
      shell: bash
      run: ./aws_ec2.sh requirements
      working-directory: ansible

    - id: create-ec2-instances
      shell: bash
      run: ./aws_ec2.sh create ${{ region }}
      working-directory: ansible

    - id: create-load-runners
      shell: bash
      run: ./aws_ec2.sh start ${{ region }}
      working-directory: ansible
